/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author User
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jTextResult = new javax.swing.JTextField();
        jBtnC = new javax.swing.JButton();
        jBtnMais = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtnMenos = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtnVezes = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtnDividir = new javax.swing.JButton();
        jBtnIgual = new javax.swing.JButton();
        jBtnPonto = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();

        jButton17.setText("jButton1");

        jButton20.setText("jButton1");

        jButton19.setText("jButton1");

        jButton18.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextResult.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jTextResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTextResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 310, 70));

        jBtnC.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnC.setText("c");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 90, 160, 80));

        jBtnMais.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnMais.setText("+");
        jBtnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMaisActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 74, 80));

        jBtn9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 74, 80));

        jBtn8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 74, 80));

        jBtn7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 74, 80));

        jBtnMenos.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnMenos.setText("-");
        jBtnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMenosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 74, 80));

        jBtn6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 74, 80));

        jBtn5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 74, 80));

        jBtn4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 74, 80));

        jBtnVezes.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnVezes.setText("*");
        jBtnVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVezesActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnVezes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 74, 80));

        jBtn3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 74, 80));

        jBtn2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 74, 80));

        jBtn1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 74, 80));

        jBtnDividir.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnDividir.setText("/");
        jBtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDividirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 74, 80));

        jBtnIgual.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnIgual.setText("=");
        jBtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 74, 80));

        jBtnPonto.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtnPonto.setText(".");
        jBtnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPontoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 74, 80));

        jBtn0.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 74, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNum(String s){
        
        String Nums = jTextResult.getText() + s;
        jTextResult.setText(Nums);
    }
    
    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
       EnterNum("7");
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        EnterNum("3");
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        EnterNum("8");
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        EnterNum("9");
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        EnterNum("6");
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        EnterNum("5");
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        EnterNum("4");
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        EnterNum("2");
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        EnterNum("1");
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        EnterNum("0");
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDividirActionPerformed
        NumEnter1 = Double.parseDouble(jTextResult.getText());
        jTextResult.setText("");
        op = "/";
    }//GEN-LAST:event_jBtnDividirActionPerformed

    private void jBtnVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVezesActionPerformed
        NumEnter1 = Double.parseDouble(jTextResult.getText());
        jTextResult.setText("");
        op = "*";
    }//GEN-LAST:event_jBtnVezesActionPerformed

    private void jBtnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMenosActionPerformed
        NumEnter1 = Double.parseDouble(jTextResult.getText());
        jTextResult.setText("");
        op = "-";
    }//GEN-LAST:event_jBtnMenosActionPerformed

    private void jBtnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMaisActionPerformed
        NumEnter1 = Double.parseDouble(jTextResult.getText());
        jTextResult.setText("");
        op = "+";
    }//GEN-LAST:event_jBtnMaisActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
       jTextResult.setText("");
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jBtnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPontoActionPerformed
        
        if(! jTextResult.getText().contains(".")){
            jTextResult.setText(jTextResult.getText() + jBtnPonto.getText());
        }
    }//GEN-LAST:event_jBtnPontoActionPerformed

    private void jBtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIgualActionPerformed
        
        NumEnter2 = Double.parseDouble(jTextResult.getText());
        
        if(op == "+"){
            Result = NumEnter1 + NumEnter2;
            jTextResult.setText(String.valueOf(Result));
        }
        else if(op == "-"){
            Result = NumEnter1 - NumEnter2;
            jTextResult.setText(String.valueOf(Result));
        }
        else if(op == "*"){
            Result = NumEnter1 * NumEnter2;
            jTextResult.setText(String.valueOf(Result));
        }
        else if(op == "/" && NumEnter1 < 0 || NumEnter1 > 0 && NumEnter2 < 0 || NumEnter2 >0){
            Result = NumEnter1 / NumEnter2;
            jTextResult.setText(String.valueOf(Result));
        }
        else{
            jTextResult.setText("Inválido!!!");
        }
    }//GEN-LAST:event_jBtnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnDividir;
    private javax.swing.JButton jBtnIgual;
    private javax.swing.JButton jBtnMais;
    private javax.swing.JButton jBtnMenos;
    private javax.swing.JButton jBtnPonto;
    private javax.swing.JButton jBtnVezes;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JTextField jTextResult;
    // End of variables declaration//GEN-END:variables
}
